# Generated by Django 5.0.3 on 2024-03-15 18:52

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_group_institution_group_updated_at'),
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUserAccount',
            fields=[
                ('deletion_marker', models.IntegerField(blank=True, help_text='Soft-deletion marker.', null=True, verbose_name='Deletion Marker')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when record was marked as deleted.', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when record was created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Date and time when record was last updated.', null=True, verbose_name='Updated At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('user_account_type', models.IntegerField(choices=[(1, 'Admin'), (2, 'Institution'), (3, 'Depot')], null=True, verbose_name='User Account Type')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentication.institution')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentication.user')),
                ('user_group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.group')),
            ],
            options={
                'verbose_name': 'historical user account',
                'verbose_name_plural': 'historical user accounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('deletion_marker', models.IntegerField(blank=True, help_text='Soft-deletion marker.', null=True, verbose_name='Deletion Marker')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date and time when record was marked as deleted.', null=True, verbose_name='Deleted At')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='Date and time when record was created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when record was last updated.', null=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('user_account_type', models.IntegerField(choices=[(1, 'Admin'), (2, 'Institution'), (3, 'Depot')], null=True, verbose_name='User Account Type')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
                ('user_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
