# Generated by Django 5.0.3 on 2024-03-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_historicaluseraccount_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='emoji',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='emojiU',
            field=models.CharField(max_length=100),
        ),
    ]
