# Generated by Django 5.0.3 on 2024-03-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_country_emoji_alter_country_emojiu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='currency',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='country',
            name='currency_symbol',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='emoji',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='country',
            name='emojiU',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso3',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='country',
            name='numeric_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='country',
            name='tld',
            field=models.CharField(max_length=20),
        ),
    ]
