# Generated by Django 5.0.3 on 2024-03-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_country_currency_alter_country_currency_symbol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoneName', models.CharField(max_length=100)),
                ('gmtOffset', models.IntegerField()),
                ('gmtOffsetName', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=50)),
                ('tzName', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='country',
            name='native',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='timezone',
            field=models.ManyToManyField(to='authentication.timezone'),
        ),
    ]
