# Generated by Django 5.0.3 on 2024-03-15 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_timezone_alter_country_native_country_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='subregion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.subregion'),
        ),
    ]
