# Generated by Django 5.0.3 on 2024-03-15 17:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryReports',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('callback_identifier', models.CharField(max_length=100, null=True)),
                ('msisdn', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('added_on', models.DateTimeField(auto_now=True, verbose_name='sent on')),
            ],
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('msisdn', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('message', models.TextField(help_text='What you want the customers message notification to read')),
                ('sent_on', models.DateTimeField(auto_now=True, verbose_name='sent on')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
            options={
                'verbose_name': 'SMS',
                'verbose_name_plural': 'SMS',
                'ordering': ['-sent_on'],
            },
        ),
    ]
